CREATE PROCEDURE DROP_ALL_PROCS
AS 
BEGIN
DROP PROCEDURE IF EXISTS LND_CreateTables;
DROP PROCEDURE IF EXISTS LND_LoadData;
DROP PROCEDURE IF EXISTS STG_CreateTables;
DROP PROCEDURE IF EXISTS STG_LoadData;
DROP PROCEDURE IF EXISTS DW_CreateTables;
DROP PROCEDURE IF EXISTS DW_LoadData;
END


EXEC DROP_ALL_PROCS

drop PROCEDURE DROP_ALL_PROCS
